[package]
name = "rndz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
# 
#

[build-dependencies]
protobuf-codegen-pure = "2" 

[dependencies]
structopt="*"
protobuf="*"
socket2={version="*", features=["all"]}
tokio={version="*", features=["full"]}
