[package]
name = "rndz"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
# 
#

[build-dependencies]
protobuf-codegen-pure = "2" 

[features]
default = ["client", "server", "async"]
server = ["tokio"]
async = ["tokio"]
client = []

[dependencies]
log="*"
env_logger="*"
structopt="*"
protobuf="*"
socket2={version="*", features=["all"]}
tokio={version="1", features=["full"], optional= true}
